In [1]:
import tensorflow as tf

In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np




In [3]:
tf.__version__

'2.11.0'

In [4]:
dir(tf.keras)

['Input',
 'Model',
 'Sequential',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__internal__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_sys',
 'activations',
 'applications',
 'backend',
 'callbacks',
 'constraints',
 'datasets',
 'dtensor',
 'estimator',
 'experimental',
 'initializers',
 'layers',
 'losses',
 'metrics',
 'mixed_precision',
 'models',
 'optimizers',
 'preprocessing',
 'regularizers',
 'utils',
 'wrappers']

In [5]:
dir(tf.keras.activations)

['__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_sys',
 'deserialize',
 'elu',
 'exponential',
 'gelu',
 'get',
 'hard_sigmoid',
 'linear',
 'relu',
 'selu',
 'serialize',
 'sigmoid',
 'softmax',
 'softplus',
 'softsign',
 'swish',
 'tanh']

In [6]:
dir(tf.keras.optimizers)

['Adadelta',
 'Adagrad',
 'Adam',
 'Adamax',
 'Ftrl',
 'Nadam',
 'Optimizer',
 'RMSprop',
 'SGD',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_sys',
 'deserialize',
 'experimental',
 'get',
 'legacy',
 'schedules',
 'serialize']

In [7]:

dir(tf.keras.regularizers)

['L1',
 'L1L2',
 'L2',
 'OrthogonalRegularizer',
 'Regularizer',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_sys',
 'deserialize',
 'get',
 'l1',
 'l1_l2',
 'l2',
 'orthogonal_regularizer',
 'serialize']

In [8]:
dir(tf.keras.models)

['Model',
 'Sequential',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_sys',
 'clone_model',
 'experimental',
 'load_model',
 'model_from_config',
 'model_from_json',
 'model_from_yaml',
 'save_model']

In [9]:
dir(tf.keras.layers)

['AbstractRNNCell',
 'Activation',
 'ActivityRegularization',
 'Add',
 'AdditiveAttention',
 'AlphaDropout',
 'Attention',
 'Average',
 'AveragePooling1D',
 'AveragePooling2D',
 'AveragePooling3D',
 'AvgPool1D',
 'AvgPool2D',
 'AvgPool3D',
 'BatchNormalization',
 'Bidirectional',
 'CategoryEncoding',
 'CenterCrop',
 'Concatenate',
 'Conv1D',
 'Conv1DTranspose',
 'Conv2D',
 'Conv2DTranspose',
 'Conv3D',
 'Conv3DTranspose',
 'ConvLSTM1D',
 'ConvLSTM2D',
 'ConvLSTM3D',
 'Convolution1D',
 'Convolution1DTranspose',
 'Convolution2D',
 'Convolution2DTranspose',
 'Convolution3D',
 'Convolution3DTranspose',
 'Cropping1D',
 'Cropping2D',
 'Cropping3D',
 'Dense',
 'DenseFeatures',
 'DepthwiseConv1D',
 'DepthwiseConv2D',
 'Discretization',
 'Dot',
 'Dropout',
 'ELU',
 'EinsumDense',
 'Embedding',
 'Flatten',
 'GRU',
 'GRUCell',
 'GaussianDropout',
 'GaussianNoise',
 'GlobalAveragePooling1D',
 'GlobalAveragePooling2D',
 'GlobalAveragePooling3D',
 'GlobalAvgPool1D',
 'GlobalAvgPool2D',
 'GlobalAvgPo

In [10]:
from tensorflow.keras.models import Sequential    # Sequencial Interface
from tensorflow.keras.layers import Dense   # Fully Connected layer

In [11]:
model = Sequential([
    
    Dense(4,
          activation= "relu",
          input_shape=(2,),
          kernel_initializer='glorot_uniform',name= "Hidden_layer"),
 
    Dense(3,
          activation= "softmax",
          kernel_initializer='glorot_uniform',name="Output_layer" )
    
])

In [12]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 Hidden_layer (Dense)        (None, 4)                 12        
                                                                 
 Output_layer (Dense)        (None, 3)                 15        
                                                                 
Total params: 27
Trainable params: 27
Non-trainable params: 0
_________________________________________________________________


In [13]:
model.weights

[<tf.Variable 'Hidden_layer/kernel:0' shape=(2, 4) dtype=float32, numpy=
 array([[ 0.43426657, -0.22718668,  0.15399837, -0.00540376],
        [ 0.49987197, -0.16285944,  0.98721695,  0.07218075]],
       dtype=float32)>,
 <tf.Variable 'Hidden_layer/bias:0' shape=(4,) dtype=float32, numpy=array([0., 0., 0., 0.], dtype=float32)>,
 <tf.Variable 'Output_layer/kernel:0' shape=(4, 3) dtype=float32, numpy=
 array([[ 0.66680884,  0.398615  , -0.44054475],
        [ 0.58990395,  0.77621186, -0.21268612],
        [-0.42855632,  0.24797869,  0.15899527],
        [ 0.15544641, -0.7821273 ,  0.844128  ]], dtype=float32)>,
 <tf.Variable 'Output_layer/bias:0' shape=(3,) dtype=float32, numpy=array([0., 0., 0.], dtype=float32)>]

In [14]:
for parameters in model.weights:
    print(parameters.shape)

(2, 4)
(4,)
(4, 3)
(3,)


In [15]:
model.weights[0].numpy()

array([[ 0.43426657, -0.22718668,  0.15399837, -0.00540376],
       [ 0.49987197, -0.16285944,  0.98721695,  0.07218075]],
      dtype=float32)

In [16]:
for parameters in model.weights:
    
    print(parameters.numpy())

[[ 0.43426657 -0.22718668  0.15399837 -0.00540376]
 [ 0.49987197 -0.16285944  0.98721695  0.07218075]]
[0. 0. 0. 0.]
[[ 0.66680884  0.398615   -0.44054475]
 [ 0.58990395  0.77621186 -0.21268612]
 [-0.42855632  0.24797869  0.15899527]
 [ 0.15544641 -0.7821273   0.844128  ]]
[0. 0. 0.]


In [17]:
# tf.keras.optimizers.Adam(
#     learning_rate=0.001,
#     beta_1=0.9,
#     beta_2=0.999,
#     epsilon=1e-07,
#     amsgrad=False,
#     weight_decay=None,
#     clipnorm=None,
#     clipvalue=None,
#     global_clipnorm=None,
#     use_ema=False,
#     ema_momentum=0.99,
#     ema_overwrite_frequency=None,
#     jit_compile=True,
#     name='Adam',
#     **kwargs,
# )

In [18]:
model.compile(
    
    optimizer = tf.keras.optimizers.Adam(learning_rate=0.5),
    loss = "categorical_crossentropy",
    metrics = ["Accuracy"]
           
)

In [19]:

df = pd.read_csv("spiral.csv")
df.head()

X = df.iloc[:,:-1].to_numpy()
y = df.iloc[:,-1].to_numpy()

y = pd.get_dummies(y).to_numpy()

In [20]:
model.fit(X,y,
         epochs=100,
          batch_size=300,
          verbose= 1
         )

Epoch 1/100
1/1 [==============================] - 0s 482ms/step - loss: 1.0712 - Accuracy: 0.3867
Epoch 2/100
1/1 [==============================] - 0s 6ms/step - loss: 0.8963 - Accuracy: 0.5400
Epoch 3/100
1/1 [==============================] - 0s 6ms/step - loss: 0.8607 - Accuracy: 0.6100
Epoch 4/100
1/1 [==============================] - 0s 7ms/step - loss: 0.8483 - Accuracy: 0.5100
Epoch 5/100
1/1 [==============================] - 0s 5ms/step - loss: 0.7904 - Accuracy: 0.5267
Epoch 6/100
1/1 [==============================] - 0s 8ms/step - loss: 0.8298 - Accuracy: 0.5733
Epoch 7/100
1/1 [==============================] - 0s 5ms/step - loss: 0.7851 - Accuracy: 0.5233
Epoch 8/100
1/1 [==============================] - 0s 8ms/step - loss: 0.7553 - Accuracy: 0.5667
Epoch 9/100
1/1 [==============================] - 0s 4ms/step - loss: 0.7122 - Accuracy: 0.6000
Epoch 10/100
1/1 [==============================] - 0s 10ms/step - loss: 0.6868 - Accuracy: 0.6033
Epoch 11/100
1/1 [========

In [21]:
model.fit(X,y,
         epochs=100,
          batch_size=300,
          verbose= 1
         )

Epoch 1/100
1/1 [==============================] - 0s 8ms/step - loss: 0.3890 - Accuracy: 0.8033
Epoch 2/100
1/1 [==============================] - 0s 7ms/step - loss: 0.3894 - Accuracy: 0.8200
Epoch 3/100
1/1 [==============================] - 0s 7ms/step - loss: 0.3875 - Accuracy: 0.7900
Epoch 4/100
1/1 [==============================] - 0s 6ms/step - loss: 0.3867 - Accuracy: 0.7767
Epoch 5/100
1/1 [==============================] - 0s 6ms/step - loss: 0.3862 - Accuracy: 0.7500
Epoch 6/100
1/1 [==============================] - 0s 5ms/step - loss: 0.3854 - Accuracy: 0.7633
Epoch 7/100
1/1 [==============================] - 0s 6ms/step - loss: 0.3845 - Accuracy: 0.7767
Epoch 8/100
1/1 [==============================] - 0s 5ms/step - loss: 0.3833 - Accuracy: 0.8333
Epoch 9/100
1/1 [==============================] - 0s 6ms/step - loss: 0.3817 - Accuracy: 0.8400
Epoch 10/100
1/1 [==============================] - 0s 6ms/step - loss: 0.3810 - Accuracy: 0.7967
Epoch 11/100
1/1 [===========

In [22]:
model.fit(X,y,
         epochs=50,
          batch_size=300,
          verbose= 1
         )

Epoch 1/50
1/1 [==============================] - 0s 7ms/step - loss: 0.3687 - Accuracy: 0.8467
Epoch 2/50
1/1 [==============================] - 0s 7ms/step - loss: 0.3687 - Accuracy: 0.8467
Epoch 3/50
1/1 [==============================] - 0s 5ms/step - loss: 0.3686 - Accuracy: 0.8500
Epoch 4/50
1/1 [==============================] - 0s 8ms/step - loss: 0.3686 - Accuracy: 0.8467
Epoch 5/50
1/1 [==============================] - 0s 4ms/step - loss: 0.3687 - Accuracy: 0.8500
Epoch 6/50
1/1 [==============================] - 0s 5ms/step - loss: 0.3686 - Accuracy: 0.8467
Epoch 7/50
1/1 [==============================] - 0s 5ms/step - loss: 0.3686 - Accuracy: 0.8467
Epoch 8/50
1/1 [==============================] - 0s 5ms/step - loss: 0.3685 - Accuracy: 0.8500
Epoch 9/50
1/1 [==============================] - 0s 5ms/step - loss: 0.3686 - Accuracy: 0.8467
Epoch 10/50
1/1 [==============================] - 0s 6ms/step - loss: 0.3685 - Accuracy: 0.8467
Epoch 11/50
1/1 [======================

###  During backpropagation, which of the following activation functions is/are not suitable for hidden layers if we wish to avoid the problem of vanishing gradient?

Correct option :

- Tanh
- Sigmoid
- Binary step

##### Explanation :


- Backpropagation calculates the gradient of the loss function to update the parameters of the neural network.
- Tanh and sigmoid functions suffer from vanishing gradient problems when the gradient approaches zero as more and more layers are used in backpropagation. 
https://machinelearningmastery.com/how-to-fix-vanishing-gradients-using-the-rectified-linear-activation-function/
- The binary step function is not used because its derivative at all points is zero, which does not help in backpropagation.